const api = require('../../utils/api')
Page({
  data: { id: '', placeId: '', collection: null, places: [], place: null, loading: true, error: '' },
  onLoad(options) { this.setData({ id: options.id || '', placeId: options.placeId || '' }); this.load() },
  load() { api.getCollection(this.data.id).then((data) => { const collection = data.collection || data; const labels = data.labels || collection.labels || []; const labelNames = Object.fromEntries(labels.map((label) => [Number(label.id), label.name])); const rawPlaces = data.places || collection.places || []; const places = rawPlaces.map((item) => ({ ...item, label_names: (item.label_ids || []).map((id) => labelNames[Number(id)]).filter(Boolean) })); const place = places.find((item) => String(item.id) === String(this.data.placeId)) || places[0] || null; this.setData({ collection, places, place, loading: false }) }).catch((err) => this.setData({ loading: false, error: err.message || '收藏清单加载失败' })) },
  back() { wx.navigateBack({ delta: 1 }) },
  openMap(e) { const index = e?.currentTarget?.dataset?.index; const p = index === undefined ? this.data.place : this.data.places[index]; if (p?.lat != null) wx.navigateTo({ url: `/pages/map/map?lat=${p.lat}&lng=${p.lng}` }) },
  setStatus(event) { const status = event.currentTarget.dataset.status; const place = this.data.place; if (!place || !status || place.status === status) return; api.setCollectionPlaceStatus(place.id, status).then(() => { this.setData({ 'place.status': status }); wx.showToast({ title: status === 'visited' ? '已标记为去过' : status === 'want' ? '已标记为想去' : '已改为有兴趣', icon: 'success' }) }).catch((err) => wx.showToast({ title: err.errMsg || '状态更新失败', icon: 'none' })) },
  cycleStatus() { const place = this.data.place; if (!place) return; const next = ({ idea: 'want', want: 'visited', visited: 'idea' })[place.status] || 'want'; this.setStatus({ currentTarget: { dataset: { status: next } } }) },
  copyLink(event) { const url = event.currentTarget.dataset.url; if (!url) return; wx.setClipboardData({ data: url, success: () => wx.showToast({ title: '链接已复制', icon: 'success' }) }) },
  copyToTrip() { const place = this.data.place; if (!place) return; api.listTrips().then((data) => { const trips = data.trips || data || []; if (!trips.length) return wx.showToast({ title: '还没有可复制的行程', icon: 'none' }); wx.showActionSheet({ itemList: trips.map((trip) => trip.title || `行程 ${trip.id}`), success: (result) => api.copyCollectionPlacesToTrip({ trip_id: Number(trips[result.tapIndex].id), place_ids: [Number(place.id)], force: false }).then(() => wx.showToast({ title: '已复制到行程', icon: 'success' })).catch((err) => wx.showToast({ title: err.errMsg || '复制失败', icon: 'none' })) }) }).catch((err) => wx.showToast({ title: err.errMsg || '行程加载失败', icon: 'none' })) },
  removePlace() { const place = this.data.place; if (!place) return; wx.showModal({ title: '移出这个地点？', content: '不会删除原行程中的地点。', success: (result) => { if (!result.confirm) return; api.deleteCollectionPlace(place.id).then(() => { wx.showToast({ title: '已移出', icon: 'success' }); wx.navigateBack({ delta: 1 }) }).catch((err) => wx.showToast({ title: err.errMsg || '移出失败', icon: 'none' })) } }) },
})
